version: '3.4'

services:
  request_generator:
    build: ./RequestGenerator
    restart: always
    ports:
      - "8001:80"
  request_executor:
    build: ./RequestExecutor
    restart: always
    depends_on:
      - "rabbitmq"
      - "request_generator"
    ports:
      - "8000:80"
    environment:
      - "RequestGeneration:EndpointBaseUrl=http://request_generator:8001/"
  response_consumer:
    build: ./ResponseConsumer
    restart: always
    depends_on:
      - "catalogdb"
      - "rabbitmq"

  catalogdb:
    container_name: catalogdb
    image: "mongo"
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
