version: '3.4'

services:
  request_generator:
    build: ./RequestGenerator
    restart: always
  request_executor:
    build: ./RequestExecutor
    restart: always
    depends_on:
      - "rabbitmq"
  response_consumer:
    build: ./ResponseConsumer
    restart: always
    depends_on:
      - "catalogdb"
      - "rabbitmq"

  catalogdb:
    container_name: catalogdb
    image: mongo
    restart: always
    volumes:
      — ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
    — "27017:27017"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"